// pwa/src/components/EditWishlistModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
    <div class="bg-white rounded-xl shadow-xl w-full max-w-lg transform transition-all">
      <!-- Header -->
      <div class="flex items-center justify-between px-6 py-4 border-b border-gray-100">
        <h2 class="text-xl font-semibold text-gray-900">{{ t.modals.editWishlist.title }}</h2>
        <button
          @click="onClose"
          class="text-gray-400 hover:text-gray-500 transition-colors p-1 hover:bg-gray-50 rounded-full"
        >
          <X class="h-5 w-5" />
        </button>
      </div>

      <!-- Form -->
      <form @submit.prevent="handleSubmit" class="p-6 space-y-6">
        <div v-if="error" class="p-3.5 rounded-lg bg-error/10 border border-error/20 text-error text-sm">
          {{ error }}
        </div>

        <!-- Name Field -->
        <div class="space-y-2">
          <label for="name" class="block text-sm font-medium text-gray-700">
            {{ t.modals.editWishlist.name.label }}
          </label>
          <input
            id="name"
            type="text"
            v-model="name"
            required
            :placeholder="t.modals.editWishlist.name.placeholder"
            class="w-full px-3.5 py-2.5 rounded-lg border border-gray-300 shadow-sm 
              text-gray-900 text-sm placeholder:text-gray-400
              focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary
              transition-colors"
          />
        </div>

        <!-- Description Field -->
        <div class="space-y-2">
          <label for="description" class="block text-sm font-medium text-gray-700">
            {{ t.modals.editWishlist.description.label }}
          </label>
          <textarea
            id="description"
            v-model="description"
            :placeholder="t.modals.editWishlist.description.placeholder"
            rows="3"
            class="w-full px-3.5 py-2.5 rounded-lg border border-gray-300 shadow-sm 
              text-gray-900 text-sm placeholder:text-gray-400
              focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary
              resize-none transition-colors h-32"
          />
        </div>

        <!-- Due Date Field -->
        <div class="space-y-2">
          <label for="dueDate" class="block text-sm font-medium text-gray-700">
            {{ t.modals.editWishlist.dueDate.label }}
          </label>
          <div class="relative">
            <input
              type="date"
              id="dueDate"
              v-model="dueDate"
              :placeholder="t.modals.editWishlist.dueDate.placeholder"
              class="w-full px-3.5 py-2.5 rounded-lg border border-gray-300 shadow-sm 
                text-gray-900 text-sm placeholder:text-gray-400
                focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary
                transition-colors
                [&::-webkit-calendar-picker-indicator]:opacity-0
                [&::-webkit-calendar-picker-indicator]:w-full
                [&::-webkit-calendar-picker-indicator]:h-full
                [&::-webkit-calendar-picker-indicator]:absolute
                [&::-webkit-calendar-picker-indicator]:top-0
                [&::-webkit-calendar-picker-indicator]:left-0
                [&::-webkit-calendar-picker-indicator]:cursor-pointer"
            />
            <Calendar class="absolute right-3.5 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400 pointer-events-none" />
          </div>
        </div>

        <!-- Actions -->
        <div class="flex justify-end gap-3 mt-6">
          <button
            type="button"
            @click="onClose"
            :disabled="isSubmitting"
            class="px-4 py-2.5 text-sm font-medium text-gray-700 hover:text-gray-800 
              hover:bg-gray-50 rounded-lg transition-colors"
          >
            {{ t.modals.editWishlist.actions.cancel }}
          </button>
          <button
            type="submit"
            :disabled="isSubmitting"
            class="px-4 py-2.5 text-sm font-medium text-white bg-primary 
              hover:bg-primary-dark rounded-lg focus:outline-none focus:ring-2 
              focus:ring-offset-2 focus:ring-primary disabled:opacity-50 
              disabled:cursor-not-allowed transition-colors inline-flex items-center"
          >
            <Loader2 v-if="isSubmitting" class="animate-spin -ml-1 mr-2 h-4 w-4" />
            {{ t.modals.editWishlist.actions.save }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { X, Calendar, Loader2 } from 'lucide-vue-next'
import { useTranslations } from '@/composables/useTranslations'

interface InitialData {
  name: string
  description: string
  dueDate?: string
}

const props = defineProps<{
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: { name: string; description: string; dueDate?: string | null }) => Promise<void>
  initialData: InitialData
}>()

const t = useTranslations()
const name = ref(props.initialData.name)
const description = ref(props.initialData.description)
const dueDate = ref(props.initialData.dueDate || '')
const isSubmitting = ref(false)
const error = ref<string | null>(null)

// Update form when initialData changes
watch(() => props.initialData, (newData) => {
  name.value = newData.name
  description.value = newData.description
  dueDate.value = newData.dueDate || ''
})

async function handleSubmit() {
  isSubmitting.value = true
  error.value = null
  
  try {
    await props.onSubmit({
      name: name.value,
      description: description.value,
      dueDate: dueDate.value || null
    })
    props.onClose()
  } catch {
    error.value = t.modals.editWishlist.errors.failedToUpdate
  } finally {
    isSubmitting.value = false
  }
}
</script>

// frontend/src/components/EditWishlistModal.tsx
'use client'

import { Dialog } from '@headlessui/react'
import { X, Calendar } from 'lucide-react'
import { useState } from 'react'
import Modal from '@/components/Modal'
import Button from '@/components/Button'

interface EditWishlistModalProps {
  isOpen: boolean
  onClose: () => void
  onSubmit: (data: { name: string; description: string; dueDate?: string | null }) => Promise<void>
  initialData: {
    name: string
    description: string
    dueDate?: string
  }
}

export default function EditWishlistModal({ isOpen, onClose, onSubmit, initialData }: EditWishlistModalProps) {
  const [name, setName] = useState(initialData.name)
  const [description, setDescription] = useState(initialData.description)
  const [dueDate, setDueDate] = useState(initialData.dueDate || '')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    setError(null)
    
    try {
      await onSubmit({
        name,
        description,
        dueDate: dueDate || null
      })
      onClose()
    } catch (err) {
      setError('Failed to update wishlist. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <div className="relative">
        <button
          onClick={onClose}
          className="absolute top-2 right-2 p-1 rounded-lg hover:bg-gray-100 transition-colors"
        >
          <X className="h-5 w-5 text-gray-500" />
        </button>

        <div className="p-6">
          <Dialog.Title as="h3" className="text-lg font-semibold mb-4">
            Edit Wishlist
          </Dialog.Title>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="name" className="block text-sm font-medium mb-1">
                Wishlist Name
              </label>
              <input
                id="name"
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
              />
            </div>

            <div>
              <label htmlFor="description" className="block text-sm font-medium mb-1">
                Description
              </label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent h-32"
              />
            </div>

            <div>
              <label htmlFor="dueDate" className="block text-sm font-medium mb-1">
                Due Date (optional)
              </label>
              <div className="relative">
                <input
                  id="dueDate"
                  type="date"
                  value={dueDate}
                  onChange={(e) => setDueDate(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
                />
                <Calendar className="h-5 w-5 text-gray-400 absolute right-3 top-2.5 pointer-events-none" />
              </div>
            </div>

            {error && (
              <p className="text-red-500 text-sm">{error}</p>
            )}

            <div className="flex justify-end gap-3 mt-6">
              <Button
                type="button"
                variant="secondary"
                onClick={onClose}
                disabled={isSubmitting}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                isLoading={isSubmitting}
              >
                Save Changes
              </Button>
            </div>
          </form>
        </div>
      </div>
    </Modal>
  )
}
