// pwa/src/components/Toast.vue
<template>
  <div class="fixed bottom-4 right-4 bg-white text-text-primary px-6 py-3 rounded-lg shadow-lg flex items-center border border-border">
    <span>{{ message }}</span>
    <div v-if="action" class="ml-4">
      <button
        @click="action.onClick"
        class="text-primary hover:text-primary-dark font-medium"
      >
        {{ action.label }}
      </button>
    </div>
    <button @click="$emit('close')" class="ml-4 text-text-secondary hover:text-text-primary">
      <X class="h-4 w-4" />
    </button>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { X } from 'lucide-vue-next'

const props = defineProps<{
  message: string
  action?: {
    label: string
    onClick: () => void
  }
  duration?: number
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

onMounted(() => {
  if (props.duration) {
    setTimeout(() => {
      emit('close')
    }, props.duration)
  }
})
</script>

// frontend/src/components/Toast.tsx
import { X } from 'lucide-react'
import { useEffect } from 'react'

interface ToastProps {
  message: string
  action?: {
    label: string
    onClick: () => void
  }
  onClose: () => void
  duration?: number
  variant?: 'default' | 'error' | 'success'
}

const variants = {
  default: 'bg-gray-900',
  error: 'bg-red-600',
  success: 'bg-green-600'
}

export default function Toast({ 
  message, 
  action, 
  onClose, 
  duration = 5000,
  variant = 'default' 
}: ToastProps) {
  useEffect(() => {
    const timer = setTimeout(() => {
      onClose()
    }, duration)

    return () => clearTimeout(timer)
  }, [duration, onClose])

  return (
    <div className={`fixed bottom-4 right-4 z-50 flex items-center gap-x-4 rounded-lg ${variants[variant]} px-4 py-3 shadow-lg`}>
      <p className="text-sm text-white">{message}</p>
      {action && (
        <button
          onClick={action.onClick}
          className="text-sm font-medium text-white hover:text-gray-100 transition-colors"
        >
          {action.label}
        </button>
      )}
      <button
        onClick={onClose}
        className="text-white/70 hover:text-white transition-colors"
      >
        <X className="h-4 w-4" />
      </button>
    </div>
  )
}
