// pwa/src/components/WishlistSkeleton.vue
<template>
  <div class="bg-white rounded-lg border border-gray-200/50 shadow-sm p-5 h-[240px] flex flex-col animate-pulse">
    <!-- Header -->
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <!-- Title area -->
        <div class="flex items-start gap-2.5 mb-3">
          <div class="flex-shrink-0 mt-[2px]">
            <div class="w-5 h-5 bg-gray-200 rounded"></div>
          </div>
          <div class="h-[22px] bg-gray-200 rounded w-3/5"></div>
        </div>
        
        <!-- Description -->
        <div class="space-y-2">
          <div class="h-[18px] bg-gray-200 rounded w-full"></div>
          <div class="h-[18px] bg-gray-200 rounded w-4/5"></div>
        </div>
      </div>

      <!-- Action button placeholder -->
      <div class="w-8 h-8 p-1.5 -mr-1.5">
        <div class="w-5 h-5 bg-gray-200 rounded"></div>
      </div>
    </div>

    <!-- Footer -->
    <div class="mt-auto pt-4 border-t border-gray-100">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-4">
          <!-- Date -->
          <div class="flex items-center gap-2">
            <div class="w-5 h-5 bg-gray-200 rounded"></div>
            <div class="w-16 h-[18px] bg-gray-200 rounded"></div>
          </div>
          <!-- Items count -->
          <div class="flex items-center gap-2">
            <div class="w-5 h-5 bg-gray-200 rounded"></div>
            <div class="w-20 h-[18px] bg-gray-200 rounded"></div>
          </div>
        </div>
        <!-- Due date badge -->
        <div class="w-[72px] h-[21px] bg-gray-200 rounded-full"></div>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/WishlistSkeleton.tsx
export default function WishlistSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div className="h-8 w-32 bg-gray-200 rounded animate-pulse"></div>
        <div className="h-10 w-40 bg-gray-200 rounded animate-pulse"></div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {[...Array(6)].map((_, i) => (
          <div key={i} className="bg-background rounded-lg border border-border p-6">
            <div className="flex items-start justify-between">
              <div className="space-y-3 flex-1">
                <div className="h-6 w-3/4 bg-gray-200 rounded animate-pulse"></div>
                <div className="h-4 w-1/2 bg-gray-200 rounded animate-pulse"></div>
              </div>
              <div className="h-8 w-8 bg-gray-200 rounded animate-pulse"></div>
            </div>
            <div className="mt-4 flex items-center justify-between">
              <div className="h-4 w-20 bg-gray-200 rounded animate-pulse"></div>
              <div className="flex space-x-4">
                <div className="h-6 w-6 bg-gray-200 rounded animate-pulse"></div>
                <div className="h-6 w-6 bg-gray-200 rounded animate-pulse"></div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
